### ISSUE TITLE
capacitive touch?

### ISSUE THREAD

**Issue by eried** [Fr4nkFletcher/ESP32-Marauder-Cheap-Yellow-Display#1]
hi, does this work on the version with capacitive touch?

**Comment by v7xDm1r** [comment]
> hi, does this work on the version with capacitive touch?

Are they not all capacitive? Yes it works with capacitive with the New espi library.

**Comment by Fr4nkFletcher** [comment]
The only two boards I've tested on (so far) are mentioned in the readme. One with type-c&microusb vs micro only

**Comment by eried** [comment]
oh ok, there is a [capacitive ](https://www.aliexpress.com/item/1005005865107357.html?spm=a2g0o.order_list.order_list_main.5.11c01802JpXO49) touch one, I will order and test :D

**Comment by v7xDm1r** [comment]
> oh ok, there is a [capacitive ](https://www.aliexpress.com/item/1005005865107357.html?spm=a2g0o.order_list.order_list_main.5.11c01802JpXO49) touch one, I will order and test :D

Usually you need 4 files. But I may be wrong. You'll have to wait for a replay from creator.

**Comment by Fr4nkFletcher** [comment]
@eried finally working for most of the capacitive touch boards

**Comment by Fr4nkFletcher** [comment]
@eried which board?

**Comment by eried** [comment]
> [@eried](https://github.com/eried) which board?

https://www.aliexpress.com/item/1005005865107357.html

**Comment by Fr4nkFletcher** [comment]
> https://www.aliexpress.com/item/1005005865107357.html

Works now
