### ISSUE TITLE
ipex gain antenna?

### ISSUE THREAD

**Issue by LuckyFishGeek** [Fr4nkFletcher/ESP32-Marauder-Cheap-Yellow-Display#11]
Can this ESP32 D0WDQ6 be modified with an ipex gain antenna?
PCB antenna performance is terrible
![17089392877874850459142034484187](https://github.com/Fr4nkFletcher/ESP32-Marauder-Cheap-Yellow-Display/assets/29472751/0b9fcd15-ac96-4705-b514-717ffcf50715)

**Comment by macgyverfuerarme** [comment]
Here is a how-to...
https://community.home-assistant.io/t/how-to-add-an-external-antenna-to-an-esp-board/131601

**Comment by Fr4nkFletcher** [comment]
> Here is a how-to...
> https://community.home-assistant.io/t/how-to-add-an-external-antenna-to-an-esp-board/131601

I never thought of that, thank you!
