### ISSUE TITLE
Updating using SD card method not working.

### ISSUE THREAD

**Issue by SassyNarwhal** [Fr4nkFletcher/ESP32-Marauder-Cheap-Yellow-Display#12]
Following the Justcallmekoko instructions to update using the SD card, it gets hung on rebooting. When rebooting it with the button on the back, the screen goes white and freezes. Is there a way to update to the latest firmware?

**Comment by Fr4nkFletcher** [comment]
I'll have to update it. The changes in the new version were mainly focused on the Marauder Mini, and I didn't think it would apply much to the CYD so I haven't got around to it. SD update method will not work with this

**Comment by SassyNarwhal** [comment]
Ah ok cool. Thought I was doing something wrong. Thanks!
