### ISSUE TITLE
How to add battery inside the case?

### ISSUE THREAD

**Issue by DRCRecoveryData** [Fr4nkFletcher/ESP32-Marauder-Cheap-Yellow-Display#13]
Hi,

![image](https://github.com/Fr4nkFletcher/ESP32-Marauder-Cheap-Yellow-Display/assets/85211068/88c9f616-3d1c-430c-ad7b-cf32840cd499)

I have successfully uploaded everything, but I'm curious about how to add a battery and an EEPROM blank slot on a PC for upgrading or adding an EEPROM chip ( U4 ). Can you provide guidance on this?

![image](https://github.com/Fr4nkFletcher/ESP32-Marauder-Cheap-Yellow-Display/assets/85211068/b661d9f1-8d2d-4c66-9647-02cdf5363625)

![image](https://github.com/Fr4nkFletcher/ESP32-Marauder-Cheap-Yellow-Display/assets/85211068/0203a9af-45aa-4220-acee-4a3c2bb49f9c)

**Comment by Fr4nkFletcher** [comment]
I wired a battery to the VIN/GND pins on the board side of the 4-pin connector at the bottom of the CYD. 

Check out the [CYD discord](https://discord.gg/nnezpvq) for more info/guidance on EEPROM mods

**Comment by DRCRecoveryData** [comment]
> I wired a battery to the VIN/GND pins on the board side of the 4-pin connector at the bottom of the CYD. 
> 
> Check out the [CYD discord](https://discord.gg/nnezpvq) for more info/guidance on EEPROM mods

Does vin ( vcc ) is 5v or 3.3v?

**Comment by Fr4nkFletcher** [comment]
5v comes out of the voltage regulator that VIN runs to when powered by USB. I used a PS3 controller battery at 3.7v and it works.

I found this also. I hope it helps https://github.com/hexeguitar/ESP32_TFT_PIO?tab=readme-ov-file#3-adding-psram

**Comment by DRCRecoveryData** [comment]
> 5v comes out of the voltage regulator that VIN runs to when powered by USB. I used a PS3 controller battery at 3.7v and it works.
> 
> I found this also. I hope it helps https://github.com/hexeguitar/ESP32_TFT_PIO?tab=readme-ov-file#3-adding-psram 

![265840632-f24cf723-8423-4b60-9f5e-faaa591844ba.png](https://github.com/Fr4nkFletcher/ESP32-Marauder-Cheap-Yellow-Display/assets/85211068/7fbb865d-b589-4f02-9f97-d0a0e0124a51)

How can i connect this gps and battery to 4 pin near micro usb?

**Comment by Fr4nkFletcher** [comment]
> 
> How can i connect this gps and battery to 4 pin near micro usb?
> 
Connect the GPS using the 4pin connector. A cable for this usually ships with the CYD. I soldered 2 female dupont jumpers to GND and VIN at the board side of the 4-pin connector. On my ps3 controller lipo I clipped the 2 pin female jst connector and added male dupont jumpers. Plug and play to power off easily. I could've done this cleaner but was just trying to "make it work"

**Comment by Fr4nkFletcher** [comment]
> 
> ![received_1768744496946044.jpeg](https://github.com/Fr4nkFletcher/ESP32-Marauder-Cheap-Yellow-Display/assets/85211068/b258e9a9-903f-41e1-8539-08c5c642a690)
> 
> I've print the case

Can I buy a case from you?

**Comment by DRCRecoveryData** [comment]
> 
> > 
> > ![received_1768744496946044.jpeg](https://github.com/Fr4nkFletcher/ESP32-Marauder-Cheap-Yellow-Display/assets/85211068/b258e9a9-903f-41e1-8539-08c5c642a690)
> > 
> > I've print the case
> 
> Can I buy a case from you?

You can order via jlcpcb:
https://drive.google.com/drive/folders/1L7p5DK15z0mjWqkGOaK8IW8phT9H3rf_?usp=sharing

![Screenshot_20240313-023204651.jpg](https://github.com/Fr4nkFletcher/ESP32-Marauder-Cheap-Yellow-Display/assets/85211068/25fb1de6-d0eb-4c8e-84e8-7973509146ee)

![Screenshot_20240313-023217890.jpg](https://github.com/Fr4nkFletcher/ESP32-Marauder-Cheap-Yellow-Display/assets/85211068/5755eeec-9e82-419b-af3b-f50bd84591de)

![received_7960131674014420.jpeg](https://github.com/Fr4nkFletcher/ESP32-Marauder-Cheap-Yellow-Display/assets/85211068/a90dffcf-c029-466e-bfab-1b69be0bd995)

**Comment by DRCRecoveryData** [comment]
> 
> > 
> > How can i connect this gps and battery to 4 pin near micro usb?
> > 
> Connect the GPS using the 4pin connector. A cable for this usually ships with the CYD. I soldered 2 female dupont jumpers to GND and VIN at the board side of the 4-pin connector. On my ps3 controller lipo I clipped the 2 pin female jst connector and added male dupont jumpers. Plug and play to power off easily. I could've done this cleaner but was just trying to "make it work"

Can you take picture of wirring? As i understand the gps vcc rx tx gnd connect same vcc and gnd to battery via a switch?

**Comment by Fr4nkFletcher** [comment]
I checked out the print files and it looks like there's no opening for most of the buttons/connectors of the cyd. It is cool though

**Comment by Fr4nkFletcher** [comment]
> > 
> > > 
> > > How can i connect this gps and battery to 4 pin near micro usb?
> > > 
> > Connect the GPS using the 4pin connector. A cable for this usually ships with the CYD. I soldered 2 female dupont jumpers to GND and VIN at the board side of the 4-pin connector. On my ps3 controller lipo I clipped the 2 pin female jst connector and added male dupont jumpers. Plug and play to power off easily. I could've done this cleaner but was just trying to "make it work"
> 
> Can you take picture of wirring? As i understand the gps vcc rx tx gnd connect same vcc and gnd to battery via a switch?

![20240312_163602.jpg](https://github.com/Fr4nkFletcher/ESP32-Marauder-Cheap-Yellow-Display/assets/135678866/67e2832a-5422-44fa-abc4-b1288f0abf60)

![20240312_170235.jpg](https://github.com/Fr4nkFletcher/ESP32-Marauder-Cheap-Yellow-Display/assets/135678866/2e77d79f-5ddb-42d7-89b0-b595cee1cdd8)

**Comment by Fr4nkFletcher** [comment]
Apparently I didn't clip the jst connector on the battery. Pictures for reference

**Comment by DRCRecoveryData** [comment]
![received_1513186592592885.jpeg](https://github.com/Fr4nkFletcher/ESP32-Marauder-Cheap-Yellow-Display/assets/85211068/4e4f1dcc-8540-4ab9-8e75-c52087d620ee)

![received_1117693969413334.jpeg](https://github.com/Fr4nkFletcher/ESP32-Marauder-Cheap-Yellow-Display/assets/85211068/53e23894-bce6-47b0-a444-8f3dbf2c5052)

The button maybe 15mm or 16mm

**Comment by Fr4nkFletcher** [comment]
I like it

**Comment by DRCRecoveryData** [comment]
The button i confirm is 15mm fit to hole, the screw is M3 12mm lenght, also does screen 2.4 inch working with firmware?

![image](https://github.com/Fr4nkFletcher/ESP32-Marauder-Cheap-Yellow-Display/assets/85211068/77c7609d-07cf-4903-b85d-0883c9af8fc8)

**Comment by DRCRecoveryData** [comment]
How to connect gps module on your board?
