### ISSUE TITLE
CLI command not working

### ISSUE THREAD

**Issue by Pascal-m** [Fr4nkFletcher/ESP32-Marauder-Cheap-Yellow-Display#14]
hello,
I can't place the cli commands on the CYD serial port, although I have the startup information.
Firmware version 0.13.9
Thk

**Comment by Fr4nkFletcher** [comment]
> hello, I can't place the cli commands on the CYD serial port, although I have the startup information. Firmware version 0.13.9 Thk

This is because GPS in mapped to RX/TX (gpio 1,3) I could make another option in the webflasher for w/ or w/o gps if you need. Let me know

**Comment by Pascal-m** [comment]
> > hello, I can't place the cli commands on the CYD serial port, although I have the startup information. Firmware version 0.13.9 Thk
> 
> This is because GPS in mapped to RX/TX (gpio 1,3) I could make another option in the webflasher for w/ or w/o gps if you need. Let me know

**Comment by Fr4nkFletcher** [comment]
> ok, yes if you had the option in the webflasher that would be great!! THANKS

On it

**Comment by Fr4nkFletcher** [comment]
> ok, yes if you had the option in the webflasher that would be great!! THANKS
> 
> > > hello, I can't place the cli commands on the CYD serial port, although I have the startup information. Firmware version 0.13.9 Thk
> > 
> > 
> > This is because GPS in mapped to RX/TX (gpio 1,3) I could make another option in the webflasher for w/ or w/o gps if you need. Let me know

Good to go

**Comment by Pascal-m** [comment]
> > ok, yes if you had the option in the webflasher that would be great!! THANKS
> 
> On it

Well done !!
It works like a charme (y)
Thk :)
