### ISSUE TITLE
Want to see the battery percentage

### ISSUE THREAD

**Issue by Skilledcamman** [Fr4nkFletcher/ESP32-Marauder-Cheap-Yellow-Display#19]
I want to be able to see battery percentage with tp4056

**Comment by Skilledcamman** [comment]
Not sure how this could be done

**Comment by Fr4nkFletcher** [comment]
> tp4056

Something like this might work https://www.aliexpress.us/item/3256805906634931.html?gatewayAdapt=glo2usa

More info can be found here on the ESP32Marauder wiki:
https://github.com/justcallmekoko/ESP32Marauder/wiki/battery

**Comment by Skilledcamman** [comment]
> > tp4056
> 
> Something like this might work https://www.aliexpress.us/item/3256805906634931.html?gatewayAdapt=glo2usa
> 
> More info can be found here on the ESP32Marauder wiki: https://github.com/justcallmekoko/ESP32Marauder/wiki/battery

though you wouldnt be able to see it on the screen? also why does the boot configuring battery interface what is that?

**Comment by Skilledcamman** [comment]
would I be able to implement it without i2c
and use tp4056 voltage and read it through io35
