### ISSUE TITLE
Bin file doesn't seem to work 

### ISSUE THREAD

**Issue by ashdavely** [Fr4nkFletcher/ESP32-Marauder-Cheap-Yellow-Display#2]
Flashed bin file using the instructions for esptool. Flash completes but just get blank screen after reset.

**Comment by v7xDm1r** [comment]
> Flashed bin file using the instructions for esptool. Flash completes but just get blank screen after reset.

Did you use all 4 files needed and make sure they're in the proper location?

**Comment by ashdavely** [comment]
I followed the instructions for the webflasher. It doesn't mention other files. Just 2 bin files, the second to try if there is color issues. What did I miss?

**Comment by witnessmenow** [comment]
Did you update the address of the flash address? 0x1000 is the default, 0x10000 is what it says on the readme

**Comment by espino1** [comment]
I have flashed the .bin file to the correct address and the display doesnt work.   the log just cycles when I view it.

**Comment by JediMongoose** [comment]
Same problem here. Changed the address to 0x10000 but only get black screen.
Using a serial terminal, I get this repeated over and over:
`
rst:0x10 (RTCWDT_RTC_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
invalid header: 0xffffffff
invalid header: 0xffffffff
invalid header: 0xffffffff
invalid header: 0xffffffff
invalid header: 0xffffffff
invalid header: 0xffffffff
invalid header: 0xffffffff
ets Jul 29 2019 12:21:46
`

What are the 3 other files @v7xDm1r ?

**Comment by ashdavely** [comment]
I changed the flash address. Tried to erase beforehand also. I've noticed now that if I flash one of the CYD test projects the screen doesn't work as well.

**Comment by Fr4nkFletcher** [comment]
Working on this now. Please compile from source and let me know

**Comment by Fr4nkFletcher** [comment]
Working on this now. Please compile from source and let me know

**Comment by JediMongoose** [comment]
Used your web flasher mentioned on the home page - and now working fine - thank you! :+1:

**Comment by ctjameson** [comment]
@Fr4nkFletcher the web flasher works great. Could we get an inverted option?

**Comment by Fr4nkFletcher** [comment]
> @Fr4nkFletcher the web flasher works great. Could we get an inverted option?

All set

**Comment by ctjameson** [comment]
My dude! Can confirm working on my USB-C CYD recently acquired from Ali. 

Would it be possible to just add the inverted flag as a setting in the menu instead of having to maintain two different files/flasher sites?

**Comment by Fr4nkFletcher** [comment]
> My dude! Can confirm working on my USB-C CYD recently acquired from Ali.
> 
> Would it be possible to just add the inverted flag as a setting in the menu instead of having to maintain two different files/flasher sites?

Like this? https://fr4nkfletcher.github.io/ESP32-Marauder-Cheap-Yellow-Display/flash0.html

**Comment by ctjameson** [comment]
> Like this? https://fr4nkfletcher.github.io/ESP32-Marauder-Cheap-Yellow-Display/flash0.html

That works, but I meant inside of Marauder after install. This way you wouldn't need two different bin files to keep up with. Wasn't sure if Marauder is given that level of configuration post boot or not.
