### ISSUE TITLE
How to flash using esptool?

### ISSUE THREAD

**Issue by oxy-nereus** [Fr4nkFletcher/ESP32-Marauder-Cheap-Yellow-Display#20]
For reasons i dont know, the web serial interface you provide cant recognize my cyd on two linux computers.
can you provide the command for esptool to flash the cyd (esp32-wroom)?
I'm not exactly sure; last time i did that with cyd, the process of flashing went well, but the display was black and the backwards LED stayed red...

**Comment by Fr4nkFletcher** [comment]
This should work, let me know.

```
cd ~
git clone https://github.com/Fr4nkFletcher/Adafruit_WebSerial_ESPTool
esptool.py --port /dev/YOURSERIALPORT write_flash 0x1000 ~/Adafruit_WebSerial_ESPTool/resources/STATIC/M/CYD/esp32_marauder.ino.bootloader.bin 0x8000 ~/Adafruit_WebSerial_ESPTool/resources/STATIC/M/CYD/esp32_marauder.ino.partitions.bin 0x10000 ~/Adafruit_WebSerial_ESPTool/resources/CURRENT/esp32_marauder_v0_13_10_20240428_cyd_nogpspwn.bin
```

**Comment by Fr4nkFletcher** [comment]
> Wow, works like a charm! Thank you!

Good to hear!
