### ISSUE TITLE
CYD ESP32 ESP32-3248S035C 3.5 INCH

### ISSUE THREAD

**Issue by MoeBenMtl** [Fr4nkFletcher/ESP32-Marauder-Cheap-Yellow-Display#23]
Hello, thanks for sharing this great project/port. I flashed my ESP32-3248S035C with the online flasher everything works RGB LED animation on boot and serial console are both functional however the display stays off is there a version for the larger ESP32-3248S035C ?

**Comment by Fr4nkFletcher** [comment]
In the works!
