### ISSUE TITLE
Support request for ESP32-8048S043C-I Capacitive Touch Screen 4.3in display 

### ISSUE THREAD

**Issue by computerfreek274** [Fr4nkFletcher/ESP32-Marauder-Cheap-Yellow-Display#24]
Support request for ESP32-8048S043C-I Capacitive Touch Screen 4.3in display 

Any chance we can get this working on this display I love the 4.3 in display. Right now not much support for this display besides openhasp

**Comment by Fr4nkFletcher** [comment]
I need to order a few of these for testing. Hopefully in the future, every Sunton CYD variant will be included in the web flasher.
