### ISSUE TITLE
Sd card content

### ISSUE THREAD

**Issue by Davim09** [Fr4nkFletcher/ESP32-Marauder-Cheap-Yellow-Display#26]
hey! what files i need to put on sd card from this project?? please specify them.

**Comment by Fr4nkFletcher** [comment]
None are required for Marauder to function but if you want Evil Portal to work check [this](https://github.com/Fr4nkFletcher/ESP32-Marauder-Cheap-Yellow-Display/tree/master/Evil%20Portal). From there, you will see a portals directory containing some examples. Place these in the root of your SD and follow the instructions at that link for the actual workflow.
