### ISSUE TITLE
GPS

### ISSUE THREAD

**Issue by HACKERprise** [Fr4nkFletcher/ESP32-Marauder-Cheap-Yellow-Display#27]
The GPS is taking a long time to connect and catch satellites, Sometimes I even reboot several times But it says it's connected.

**Comment by Fr4nkFletcher** [comment]
Which antenna are you using? It can take time to get a lock. Helps if you go outside

**Comment by stevedee78** [comment]
I have the same problem. I have installed the NEO-6M.

**Comment by HACKERprise** [comment]
> Which antenna are you using? It can take time to get a lock. Helps if you go outside

That's exactly what happens at the moment with the ceramic one.

**Comment by HACKERprise** [comment]
> Which antenna are you using? It can take time to get a lock. Helps if you go outside

That's exactly what happens at the moment with the ceramic one.

**Comment by HACKERprise** [comment]
But I would like to change the antenna, what do you recommend, and the Wi-Fi one too?

**Comment by Fr4nkFletcher** [comment]
I use the NEO6MV2 with this antenna without issue https://a.co/d/be2EhWE

As for wifi, I use an Alfa 9dBi antenna for most projects 
https://a.co/d/1KuWTSE

I hope this helps

**Comment by Fr4nkFletcher** [comment]
Will work on this today to make it better somehow.

**Comment by Fr4nkFletcher** [comment]
![Screenshot_20240529_110549_GitHub.jpg](https://github.com/Fr4nkFletcher/ESP32-Marauder-Cheap-Yellow-Display/assets/135678866/8204aad3-ef0f-4add-8e38-3354b1d31454)

https://github.com/justcallmekoko/ESP32Marauder/issues/338
