### ISSUE TITLE
Evil portal

### ISSUE THREAD

**Issue by HACKERprise** [Fr4nkFletcher/ESP32-Marauder-Cheap-Yellow-Display#28]
I've already put the files in a folder and nothing appears when I call, can someone help me?

**Comment by Fr4nkFletcher** [comment]
https://github.com/Fr4nkFletcher/ESP32-Marauder-Cheap-Yellow-Display/issues/26

**Comment by HACKERprise** [comment]
I already managed to do it, but when I start the evil portal... Say could not find /ap.config.txt.
Touch to exit...

**Comment by Fr4nkFletcher** [comment]
![sc000000](https://github.com/Fr4nkFletcher/ESP32-Marauder-Cheap-Yellow-Display/assets/135678866/8c50e8fa-1449-4ec4-bafc-161a28bdd67b)

**Comment by HACKERprise** [comment]
Very clear, everything resolved hehehe
