### ISSUE TITLE
No WPS support ?

### ISSUE THREAD

**Issue by OldMateAidos** [Fr4nkFletcher/ESP32-Marauder-Cheap-Yellow-Display#30]
Would be awesome to see any form of WPS brute force/pixie attacks implemented

**Comment by Fr4nkFletcher** [comment]
> Would be awesome to see any form of WPS brute force/pixie attacks implemented

100% agree it would be nice. It's theoretically possible but wouldn't be very practical I think due to the hardware just not being enough for this use case.

**Comment by OldMateAidos** [comment]
Yh fair enough , I'm looking at trying to port over WPS features I'll fork and push if I manage it gets it working :)

**Comment by Fr4nkFletcher** [comment]
> Yh fair enough , I'm looking at trying to port over WPS features I'll fork and push if I manage it gets it working :)

Sounds good to me!

**Comment by OldMateAidos** [comment]
https://github.com/espressif/esp-idf hopefully I can start here has WPS support
