### ISSUE TITLE
Blackscreen with ESP32-24325024R /driver chip ST7789

### ISSUE THREAD

**Issue by xxjeanxx80** [Fr4nkFletcher/ESP32-Marauder-Cheap-Yellow-Display#32]
I thought that buying any yellow ESP type would work, but when I flashed two versions, one with a micro USB port and one with two USB ports, the flashing was successful. However, when I unplugged the power and plugged it back in, the screen didn't show anything. Can anyone help me?

**Comment by xxjeanxx80** [comment]
![image](https://github.com/Fr4nkFletcher/ESP32-Marauder-Cheap-Yellow-Display/assets/87995010/7f1ba289-785e-4011-be06-bbcfa3454aca)
Here is the picture

**Comment by Fr4nkFletcher** [comment]
It looks like you're using the 2.4" CYD variant. Unfortunately, for now, only the 2.8" modules are supported by this webflasher
