### ISSUE TITLE
ESP32-2432S024 not work display

### ISSUE THREAD

**Issue by Asmodeux2** [Fr4nkFletcher/ESP32-Marauder-Cheap-Yellow-Display#33]
Will there be support for 2.4 inch screens or how can I make the screen work?

**Comment by Fr4nkFletcher** [comment]
I'll have mine ready soon but this fork should get you there if you can't wait 

https://github.com/lsdlsd88/ESP32-Marauder-Cheap-Yellow-Display

**Comment by Asmodeux2** [comment]
Fr4nkFletcher thanks for the tip. But no matter how much time I spend I can't get the project to compile trivially because of various errors. I realized that I need to _change parameters in User_Setup.h from TFT_eSPI library_. But at the moment of compilation everything is very tight. Please make different variations of screens in your CYD-Flasher. Thanks before.

P.S I am very stupid

**Comment by Fr4nkFletcher** [comment]
@Asmodeux2 msg me on discord:@0xbangbang if you have the 2.4 cap and can test a bin

**Comment by Fr4nkFletcher** [comment]
@Asmodeux2 https://github.com/Fr4nkFletcher/ESP32-Marauder-Cheap-Yellow-Display/commit/13ced215b7e8f2e90074205df57b2b9ce2a4e932
