### ISSUE TITLE
this is not an issue its a request to get a portable version for ELECROW ESP32 display-2.8 Inch HMI 240×320 Display SPI TFT LCD Touch Screen Compatible with Arduino

### ISSUE THREAD

**Issue by a5w1na5t60** [Fr4nkFletcher/ESP32-Marauder-Cheap-Yellow-Display#36]
hello Fr4nkFletcher 
can you port this project for ELECROW ESP32 display-2.8 Inch HMI 240×320 Display SPI TFT LCD Touch Screen Compatible like cheap yellow display, the connections are exactly same but the only difference is this module has a TFT-LCD with driver IC ILI9341V not the ILI9341V , the reason i post this issue because in India we cant buy this cheap yellow display and this ELECROW is the only alternative...
so can you please port this marauder firmware

**Comment by Fr4nkFletcher** [comment]
I've seen those a few times recently. I'll try to add this to the list when I start ordering modules so I can expand compatibility
