### ISSUE TITLE
GUITION JC2432W328 ESP-32 2,8" support

### ISSUE THREAD

**Issue by maxpill** [Fr4nkFletcher/ESP32-Marauder-Cheap-Yellow-Display#37]
The JC2432W328 ESP-32 2.8" web flasher successfully uploads code, but the display remains black. This issue persists despite multiple attempts. Tried all of the possible Marauder versions in the web flasher.

### To Reproduce

1. Upload Marauder to the JC2432W328 ESP-32 board using web flasher.

### Expected Behavior

The display should show the Marauder instead of remaining black.

### Actual Behavior

The display stays black after uploading the code. Serial console shows Marauder initializing properly.

### Board

[Aliexpress JC2432W328 ESP-32](https://aliexpress.com/item/1005006729707613.html)

As per boards manual (attached) it seems to use ST7789 (Page 15 in manual) and standard 240x320 resolution. Pinout for display also attached (Page 16 in manual).

[Download whole user manual JC2432W328.pdf](https://github.com/user-attachments/files/16638364/Getting.started.JC2432W328.pdf)

![15](https://github.com/user-attachments/assets/19bad9d1-a2dd-4469-ad1b-31540d2d39b5)
![16](https://github.com/user-attachments/assets/c4c0d0c4-2a8a-4d42-937b-b8f1600df3b1)
<img width="592" alt="Pinout" src="https://github.com/user-attachments/assets/96c0ddc1-832d-49f0-b6c7-e786db1802cb">

**Comment by maxpill** [comment]
Got it running omg :) I'd be happy to help adding it to your tool.

![image](https://github.com/user-attachments/assets/329f5d52-2471-4d61-bd6f-23a92cb6b718)

![image](https://github.com/user-attachments/assets/50ee2df6-f3a5-45aa-a98d-b5d5a4382fde)

**Comment by Fr4nkFletcher** [comment]
If you want you could send the bins and I could add it to the flasher. Nice work man

**Comment by maxpill** [comment]
> If you want you could send the bins and I could add it to the flasher. Nice work man

Sure, I will link binaries in this issue. However I will test the firmware first, because I've already noticed some minor bugs regarding led pinout etc.

> You can change it to black bg by going into tft-espi user_setup.h and changing #define TFT_INVERSION to on/off

Already did, thanks :)

**Comment by maxpill** [comment]
After further investigation, it appears that this display utilizes I2C Capacitive touch rather than the typical resistive touch used by CYD. Keeping my fingers crossed for a successful port to capacitive touch.

**Comment by zidanjulio** [comment]
can I use it with a 3.5″ screen? Can I flash it directly on a website with a 3.5 screen?
I tried it before on a 2.8 screen and it worked.

**Comment by maxpill** [comment]
> can I use it with a 3.5″ screen? Can I flash it directly on a website with a 3.5 screen?
> 
> I tried it before on a 2.8 screen and it worked.

What display controller does your board use?

**Comment by zidanjulio** [comment]
like this 
![IMG_3062](https://github.com/user-attachments/assets/27da3ae7-c7e9-4a96-a940-20c71df61f6c)

**Comment by Shirtsy** [comment]
@maxpill I have the same model of CYD, what changes did you have to make to get it to work? I'm curious to tinker with it myself.

**Comment by xxjeanxx80** [comment]
I have a problem that, although not very serious, is still not trivial. Currently, after successfully uploading to my CYD, it does not recognize my touch input.
CYD : ESP32-2432S024R.  Although my box says  ST7789, I can only upload based on ILI9341 in User_Setup.h
https://github.com/user-attachments/assets/7dd5f359-eef6-4f68-b6ab-5b3114ba05fa
![Screenshot 2024-09-10 173042](http
![Screenshot 2024-09-10 173014](https://github.com/user-attachments/assets/9479c9cd-f05e-4443-9f51-94d38f326129)
s://github.com/user-attachments/assets/9c526aa4-4938-4f44-86d1-13b211e8054d)

**Comment by maxpill** [comment]
> @maxpill I have the same model of CYD, what changes did you have to make to get it to work? I'm curious to tinker with it myself.

I will create a fork of this repo on my GitHub, but recently I'm short on time. Basically, there are a few things you need to do to get it running:

### Setup and Compilation

1. Set up your Arduino IDE to be able to compile this repository. You can use these two repos as guides:
	* https://github.com/smoochiee/MARAUDER-FOR-CYD---CHEAP-YELLOW-DISPLAY
	* https://github.com/justcallmekoko/ESP32Marauder/wiki/installing-firmware-from-source

### Board Information

2. Collect info on your particular board model as I did. What you need to know is:
	* Display pinout (as shown in the documentation I attached in this issue)
	* Display controller
	* Touch type (capacitive/resistive)
	* Touch controller

### Flashing and Testing

3. You can probably flash this Marauder software directly on your board using @Fr4nkFletcher's webflasher, and then use a serial console tool to see if it's functional.

### Display Configuration

4. To get the display working, you have to set up `User_Setup.h` with the proper pinout. You will also need to modify the repository Marauder code to work with your display controller.

### Touch Configuration

5. To get touch working, it's a bit harder:
	* If you have resistive touch, chances are it will work out of the box.
	* If not, you have to adjust the `calData` values.
	* If you have capacitive touch, you better wait for my repo. You have to basically change all the touch-related code in this repo, as the capacitive touch is handled totally differently.

**Comment by zidanjulio** [comment]
How? Can the board that I sent with a 3.5inch screen be flashed directly through the webflasher?

**Comment by maxpill** [comment]
> How? Can the board that I sent with a 3.5inch screen be flashed directly through the webflasher?

You can give it a try, with high degree of certainty the Marauder will work, but display will not.

**Comment by Fr4nkFletcher** [comment]
@maxpill any updates sir?

**Comment by VNEvil** [comment]
Hi @maxpill 
Is your archive complete?

**Comment by maxpill** [comment]
@Fr4nkFletcher  @VNEvil Hello again. It is partially done, however I am recently very short on time, and as this is my hobby project it is not my priority recently.

**Comment by Fr4nkFletcher** [comment]
@maxpill https://github.com/Fr4nkFletcher/ESP32-Marauder-Cheap-Yellow-Display/commit/5dd31b471d798256c70c959492d714ddd7612fd4 send me a link to your board's tft_espi libs and i will make you a bin if you want

**Comment by Fr4nkFletcher** [comment]
@maxpill msg me on discord:0xbangbang if you still want to get this going

**Comment by DangerLarry10** [comment]
@Fr4nkFletcher @maxpill  any chance you guys actually did get this going?? I thought I was close but I've got Cap display
