### ISSUE TITLE
No marauder logo splash screen on boot

### ISSUE THREAD

**Issue by PigeonFX** [Fr4nkFletcher/ESP32-Marauder-Cheap-Yellow-Display#39]
Hi, I don't get the Marauder logo splash screen with esp32_marauder_v0_13_10_20240426_cyd2usb_nogpspwn.bin

**Comment by Fr4nkFletcher** [comment]
This is the latest commit per @justcallmekoko

**Comment by Fr4nkFletcher** [comment]
@PigeonFX you can flash previous versions now. Check out the webflasher
