### ISSUE TITLE
2.4 tft cheap yellow screen

### ISSUE THREAD

**Issue by tuanhuy-gif** [Fr4nkFletcher/ESP32-Marauder-Cheap-Yellow-Display#40]
can i use it with 2.4 screen, hve any solution for me??

**Comment by Fr4nkFletcher** [comment]
Not right now, but hopefully soon. Check out the closed issues on the 2.4 for reference

**Comment by Fr4nkFletcher** [comment]
@tuanhuy-gif try now on the resistive touch version
