### ISSUE TITLE
Cannot get touch functionality on ESP32-2432S024

### ISSUE THREAD

**Issue by xxjeanxx80** [Fr4nkFletcher/ESP32-Marauder-Cheap-Yellow-Display#42]
I have a problem that, although not very serious, is still not trivial. Currently, after successfully uploading to my CYD, it does not recognize my touch input.
CYD : ESP32-2432S024R.  Although my box says  ST7789, I can only upload based on ILI9341 in User_Setup.h

https://github.com/user-attachments/assets/7dd5f359-eef6-4f68-b6ab-5b3114ba05fa

![Screenshot 2024-09-10 173014](https://github.com/user-attachments/assets/90285631-3b2d-4d3c-a5ec-a035887b894f)

![Screenshot 2024-09-10 173042](https://github.com/user-attachments/assets/05a63fd4-8137-4725-a77e-c8ecc348ade3)

**Comment by Fr4nkFletcher** [comment]
Check out https://github.com/Fr4nkFletcher/ESP32-Marauder-Cheap-Yellow-Display/issues/40

**Comment by Fr4nkFletcher** [comment]
@xxjeanxx80 try now =]
