### ISSUE TITLE
Evil portal size too large

### ISSUE THREAD

**Issue by domia-official** [Fr4nkFletcher/ESP32-Marauder-Cheap-Yellow-Display#45]
hello i got a problem , when i launch evil portal it say : the given html is too large .The byte limit is 11400 , but i see that the limit is 20ko and my index.html file is 16.ko

![IMG_3488](https://github.com/user-attachments/assets/a91bd72f-ba0a-4f35-9807-8847ea4d7b50)
![Capture d’écran 2024-09-21 173520](https://github.com/user-attachments/assets/c2290b86-de82-4797-931a-7b4f72afe5ba)
![Capture d’écran 2024-09-21 173506](https://github.com/user-attachments/assets/c0069184-d4a4-4b0f-b8ec-838d5ba3896a)

**Comment by Fr4nkFletcher** [comment]
@domia-official can you link or share your html?

**Comment by domia-official** [comment]
[index.html.txt](https://github.com/user-attachments/files/17084699/index.html.txt)

**Comment by domia-official** [comment]
its html i just put .txt bc of github

**Comment by Fr4nkFletcher** [comment]
![image](https://github.com/user-attachments/assets/a044c989-fde7-4f81-8a2d-4e960dbb6c4e)

I renamed your file to test.html and tested on my cyd2usb. It works?

**Comment by domia-official** [comment]
[aaa.html.txt](https://github.com/user-attachments/files/17084795/aaa.html.txt)
check this one

**Comment by domia-official** [comment]
the aaa.html.txt is the real problem

**Comment by domia-official** [comment]
the problem was the svg logo , its seem to be not the real size so i use this website https://svgomg.net/ and choose the level 1 of compression . And now its good
