### ISSUE TITLE
Micro SD problems

### ISSUE THREAD

**Issue by Zynth9999** [Fr4nkFletcher/ESP32-Marauder-Cheap-Yellow-Display#47]
Hey, yes, another issue, my microsd doesnt work.
Board:
cyd2usb

Some CYDs the touch and SD SPI bus is shared, anyone figure this out yer?

**Comment by Fr4nkFletcher** [comment]
Reset until it recognizes the sd

**Comment by Zynth9999** [comment]
Doesnt work, Larry on BLOUGH discord told me it has to be implemented software side

**Comment by Zynth9999** [comment]
Still not fixed, resetting doesnt help
