### ISSUE TITLE
ep

### ISSUE THREAD

**Issue by thedog737** [Fr4nkFletcher/ESP32-Marauder-Cheap-Yellow-Display#49]
ap config not there

**Comment by Fr4nkFletcher** [comment]
https://github.com/justcallmekoko/ESP32Marauder/wiki/evilportal

**Comment by Fr4nkFletcher** [comment]
https://github.com/Fr4nkFletcher/ESP32-Marauder-Cheap-Yellow-Display/blob/master/evilportal/README.md
