### ISSUE TITLE
Input issue after using 0.13.7 flash tool

### ISSUE THREAD

**Issue by NoxiousKarn** [Fr4nkFletcher/ESP32-Marauder-Cheap-Yellow-Display#5]
It seems that when entering a rotated menu the screen rotates -90 degrees top counter clockwise but the touch controls rotate 90 degrees so top of unit rotates clockwise... I had to roll back to 0.13.5 where the problem does not exist.
https://youtu.be/UI-ROiRZYok

**Comment by ggaljoen** [comment]
Tip to solve this is in this calculation of the orientation:
lcd.setRotation(lcd.getRotation() ^ 1)

**Comment by Fr4nkFletcher** [comment]
Gotcha. Will try to find time this evening to fix and reupload

**Comment by Fr4nkFletcher** [comment]
> Pull request made

Thanks man. Will redo the bin soon, just working right now

**Comment by Fr4nkFletcher** [comment]
> It seems that when entering a rotated menu the screen rotates -90 degrees top counter clockwise but the touch controls rotate 90 degrees so top of unit rotates clockwise... I had to roll back to 0.13.5 where the problem does not exist. https://youtu.be/UI-ROiRZYok

Good to go, let me know

**Comment by NoxiousKarn** [comment]
works great now Thanks!
