### ISSUE TITLE
how do i get and set up ap config txt

### ISSUE THREAD

**Issue by thedog737** [Fr4nkFletcher/ESP32-Marauder-Cheap-Yellow-Display#50]

**Comment by Fr4nkFletcher** [comment]
https://github.com/Fr4nkFletcher/ESP32-Marauder-Cheap-Yellow-Display/issues/49

Check the two links from your other issue. The evilportal readme gives it step by step. Also, you really need to look over the Marauder wiki.

But sniff the AP you want to clone, go into WiFi general and select your AP and evilportal html.

**Comment by thedog737** [comment]
ok thank you
