### ISSUE TITLE
Change background color.

### ISSUE THREAD

**Issue by Muratik2803** [Fr4nkFletcher/ESP32-Marauder-Cheap-Yellow-Display#52]
hello, im new here and i watched a lot of videos about this cheap yellow display and i dont know why but i cant change displau background. Its different from a picture instead of black i got white background and inversions. Please help me.

Muratik2803
9/25/24

**Comment by Fr4nkFletcher** [comment]
Go into the tft-espi library user_setup.h and find the part about color inversion.

**Comment by Muratik2803** [comment]
Ty but I don’t know where it is, can you like make steps where to go.

**Comment by Fr4nkFletcher** [comment]
https://github.com/Fr4nkFletcher/ESP32-Marauder-Cheap-Yellow-Display/blob/master/libraries/TFT_eSPI-master/User_Setup.h#L115

**Comment by Muratik2803** [comment]
and the last question. Thank for your kidness and fast replying but where to put it? i dont have a micro sd translator. Maybe you can like put it in your web site(CYM WEBFLASHER) i tried to put it into terminal (#define TFT_INVERSION_OFF) and nothing happened. 
Thanks for respond
Muratik2803

**Comment by Muratik2803** [comment]
And the last question. Thank for your kindness and fast replying but where to put it? i don't have a micro SD translator. Maybe you can like put it in your web site (CYM WEBFLASHER) i tried to put it into terminal (#define TFT_INVERSION_OFF) and nothing happened.
Thanks for respond
Muratik2803 :)

**Comment by Fr4nkFletcher** [comment]
I was thinking you were compiling from source. What cheap yellow display are you using?

**Comment by Muratik2803** [comment]
It’s esp32-2432s028. And I got dark mode, in flasher instead of CYD2USB W/O GPS I picked CYD microusb only and I got dark version but when I watched the YouTube video of Talking Sasquach, he picked the CYD2USB W/O GPS. 

![image](https://github.com/user-attachments/assets/e0b16d40-ba23-4671-b347-beb5df9293dd)

**Comment by Fr4nkFletcher** [comment]
That's because he has the model with type-c and micro-usb so they call it the CYD2USB

**Comment by Muratik2803** [comment]
But which one should I use?
