### ISSUE TITLE
cant flash old bins and how

### ISSUE THREAD

**Issue by ESP32Marauder** [Fr4nkFletcher/ESP32-Marauder-Cheap-Yellow-Display#54]
so im trying to install the old 10.13 bins and it dont work so pls help and can you give me some instructions to install the old bins

**Comment by Lgndwilloske** [comment]
Use the esp flasher by espressif

**Comment by Fr4nkFletcher** [comment]
https://github.com/Fr4nkFletcher/ESP32-Marauder-Cheap-Yellow-Display/issues/48#issuecomment-2372636945

**Comment by ESP32Marauder** [comment]
and what file do i use

**Comment by ESP32Marauder** [comment]
it diddent work the screen is just white
![WIN_20240926_17_38_26_Pro](https://github.com/user-attachments/assets/4e1f964c-6d12-4b0d-b581-4bcf712f788d)

**Comment by Fr4nkFletcher** [comment]
> https://github.com/Fr4nkFletcher/ESP32-Marauder-Cheap-Yellow-Display/issues/48#issuecomment-2372636945

**Comment by Fr4nkFletcher** [comment]
@ESP32Marauder you can flash old bins from the webflasher now
