### ISSUE TITLE
Readme improvements required

### ISSUE THREAD

**Issue by srikeerthis** [Fr4nkFletcher/ESP32-Marauder-Cheap-Yellow-Display#57]
A detailed explanation about the project is required. 
Some pointers that would be useful:
- What is the project goal? (one liner) 
- Requirements for setup 
- Installation steps 
- Example usage

**Comment by Fr4nkFletcher** [comment]
> A detailed explanation about the project is required.
ok

**Comment by Fr4nkFletcher** [comment]
> A detailed explanation about the project is required.

lol ok

**Comment by Lgndwilloske** [comment]
Lmao
