### ISSUE TITLE
 Will not load into the firmware

### ISSUE THREAD

**Issue by Jasurios** [Fr4nkFletcher/ESP32-Marauder-Cheap-Yellow-Display#58]
I have an esp32 2432S024 device but in the flasher it is displayed as esp32 2432S028R

After the firmware, the LED flashes first blue green and then red when loading and shows a black screen

**Comment by Fr4nkFletcher** [comment]
Everything works but the display on these models. If you want to still use it, you can use the serial terminal for the marauder CLI

**Comment by Jasurios** [comment]
it’s a pity, but how can I make it work, maybe a driver or something else. I just live sooooooooo far from civilization and I’ve been waiting for it for 1 year and I’m not eager to order a new one for a bunch of money

**Comment by Fr4nkFletcher** [comment]
I'd have ordered the module that works already but the 2.4" is in the works hopefully it won't be long

**Comment by Jasurios** [comment]
🤚

**Comment by Lgndwilloske** [comment]
Download drivers and if that doesent work then hold boot press test and then let go of boot until the screen is black
