### ISSUE TITLE
I need help of ILI9341 LCD pinout

### ISSUE THREAD

**Issue by DRCRecoveryData** [Fr4nkFletcher/ESP32-Marauder-Cheap-Yellow-Display#59]
Hi,

Can you check where is ILI9341 LCD pinout in config.h file of CYD V1?

**Comment by Fr4nkFletcher** [comment]
Does [this](https://github.com/lsdlsd88/ESP32-Marauder-Cheap-Yellow-Display/blob/master/libraries/TFT_eSPI/User_Setup.h) help?
