### ISSUE TITLE
MicroSD Problems

### ISSUE THREAD

**Issue by Zynth9999** [Fr4nkFletcher/ESP32-Marauder-Cheap-Yellow-Display#61]
Hey, last time you told me to reset until its fixed, didnt help, SD and Touch share the same SPI bus.

**Comment by Lgndwilloske** [comment]
mind linking the issue post?

**Comment by Fr4nkFletcher** [comment]
@Zynth9999 link to the specific module you're using please. Try flashing a previous version of Marauder and let me know if anything changes

**Comment by Zynth9999** [comment]
> @Zynth9999 link to the specific module you're using please. Try flashing a previous version of Marauder and let me know if anything changes

I cant give you the link to the one i bought but its called ESP32-2432S028
Has 2 usb ports

Flashed 0.13.X - Nothing
Flashed 1.X - Still nothing

Its a software issue

As said on the CYD repo
![Screenshot_20241017_075410_GitHub.png](https://github.com/user-attachments/assets/b243e6d6-4c98-4c21-b9bc-10b4f55fd051)

**Comment by Zynth9999** [comment]
> mind linking the issue post?
> 

https://github.com/Fr4nkFletcher/ESP32-Marauder-Cheap-Yellow-Display/issues/47

**Comment by Fr4nkFletcher** [comment]
If you're using either of the linked compatible modules, the SD works. Try a different sdcard or module and let me know

**Comment by Zynth9999** [comment]
Kk will try when i get home

**Comment by Zynth9999** [comment]
Nope, didnt help

**Comment by Lgndwilloske** [comment]
have you tried flashing different firmware on the esp? I'm pretty sure there's a firmware that can mount and unmount an sd card

**Comment by Zynth9999** [comment]
> have you tried flashing different firmware on the esp? I'm pretty sure there's a firmware that can mount and unmount an sd card 

Yes i did

**Comment by Zynth9999** [comment]
> there shouldn't be an issue with the software, maybe check what sd card you're using and if its supported?

Ive tried every card i can, from my wii, phone, 2ds and a new never used card

**Comment by Fr4nkFletcher** [comment]
Take pictures of your module

**Comment by Lgndwilloske** [comment]
> > have you tried flashing different firmware on the esp? I'm pretty sure there's a firmware that can mount and unmount an sd card
> 
> Yes i did

and did it work?

**Comment by Zynth9999** [comment]
Nope it did not

**Comment by Lgndwilloske** [comment]
well if you tried a different firmware (different from the maruder firmware) and the sd card didnt work then that is a clear sign that its the ESP-32 not the firmware. I recomend you send us the link or a few images of the esp so we can assess it, thanks

**Comment by Fr4nkFletcher** [comment]
Take pictures of your module and we will continue this

**Comment by Zynth9999** [comment]
![20241023_202247.jpg](https://github.com/user-attachments/assets/bc0abfc8-1c86-494f-affe-59093a03d155)

![20241023_202305.jpg](https://github.com/user-attachments/assets/29112d27-d512-483d-9c75-737010839af8)

**Comment by Fr4nkFletcher** [comment]
It could just be the picture but GND and MOSI appear to be shorted

![image](https://github.com/user-attachments/assets/0156d807-a4e2-43ba-9880-cc0d3cfee463)

**Comment by Zynth9999** [comment]
Let me check, but on the chip itself or the sd reader

**Comment by Zynth9999** [comment]
![20241024_073102.jpg](https://github.com/user-attachments/assets/db72ccba-1250-44ff-9c12-d804873731ac)

You were right

**Comment by Zynth9999** [comment]
Yep, i cut the part whwre it was connected and it works, thanks!

**Comment by Fr4nkFletcher** [comment]
I knew there was something else going on! Glad you got it bro

**Comment by Lgndwilloske** [comment]
sorry for being absent on this case and others, have been busy this week👍
