### ISSUE TITLE
problem with touchscreen 2.4

### ISSUE THREAD

**Issue by Jasurios** [Fr4nkFletcher/ESP32-Marauder-Cheap-Yellow-Display#65]
Hello, thank you for the new firmware, but when I flashed it, I realized that the screen does not work, plus the SD card is also not visible, what should I do?

**Comment by Jasurios** [comment]
and by the way, the problem is not only with this but also with the color

**Comment by Jasurios** [comment]
Help

**Comment by Fr4nkFletcher** [comment]
@Jasurios u must have the capacitive version

**Comment by Jasurios** [comment]
capacitive version what is this? Can you help me, I'm a newbie and I don't understand.

**Comment by Jasurios** [comment]
![Uploading 17300461594095390000083285864679.jpg…]()

**Comment by Jasurios** [comment]
![Uploading 17300462131959214658134489977755.jpg…]()

**Comment by Fr4nkFletcher** [comment]
@Jasurios link to the module you purchased, please slow down though

**Comment by Jasurios** [comment]
ESP32-2432S024

**Comment by Jasurios** [comment]
I have discussed this topic before, thanks for adding the 2.4 screen option, but what about touch? For some reason it doesn't work for me.

**Comment by Fr4nkFletcher** [comment]
Send me a link to what you have

**Comment by Jasurios** [comment]
Смотри, что есть на AliExpress! Макетная плата ESP32 Arduino LVGL с Wi-Fi и Bluetooth, 2,4 дюйма, 240*320, умный экран дисплея 2,4 дюйма за 1 034,78 ₽
https://sl.aliexpress.ru/p?key=OnH1rbX

**Comment by Jasurios** [comment]
This is where I bought the version capacitive touch

**Comment by Jasurios** [comment]
![Uploading Screenshot_2024-10-27-21-29-45-379_ru.aliexpress.buyer.jpg…]()

**Comment by Jasurios** [comment]
![Uploading 17300466631694231849784834519441.jpg…]()

**Comment by Jasurios** [comment]
I look forward to your reply.

**Comment by Fr4nkFletcher** [comment]
You need the resistive touch version

**Comment by Jasurios** [comment]
But you said it was a capacious version. Okay, I'll wait for updates😞

**Comment by Jasurios** [comment]
You will make an update for this type of screen, right?

**Comment by Jasurios** [comment]
Is there another way to control instead of touch, like a mouse and keyboard?

**Comment by Fr4nkFletcher** [comment]
> But you said it was a capacious version. Okay, I'll wait for updates😞

No I was saying you must have the capacitive touch version which would be the reason it's not working for you. Only resistive right now.

**Comment by Fr4nkFletcher** [comment]
> Is there another way to control instead of touch, like a mouse and keyboard?

Yes check out the serial terminal for marauder cli access

**Comment by Fr4nkFletcher** [comment]
> You will make an update for this type of screen, right?

Yes I just need to order everything. Porting all resistive and the cap

**Comment by Fr4nkFletcher** [comment]
> It's a pity, but will there be updates that will fix this?

In time yes

**Comment by Fr4nkFletcher** [comment]
> It's a pity, but will there be updates that will fix this?

Order the modules that work for now?

**Comment by Jasurios** [comment]
It's embarrassing to ask, but could you help me with loading sketches with my device? Yesterday I installed fresh libraries but I couldn't find on the Internet how to use them for my board.

**Comment by Lgndwilloske** [comment]
an issue you have is your getting this of ali express, it's chinese, your better of ordering this stuff of amazon.co.uk the sketches thing, you can't use the ardunio ide with that esp it has to be an ardunio esp32, you will have to write the code and save it then flash it with a espressif flash tool.

**Comment by Fr4nkFletcher** [comment]
Give me some time I'm not at home

**Comment by Jasurios** [comment]
👍

**Comment by Lgndwilloske** [comment]
> Give me some time I'm not at home

see, this is what i mean, we are busy people and we most likely won't reply so it's best if you wait a day or 2 if we don't reply, if you want you can always dm me on discord @lgndwilloski

**Comment by Jasurios** [comment]
👍

**Comment by Fr4nkFletcher** [comment]
@Jasurios added here https://github.com/Fr4nkFletcher/ESP32-Marauder-Cheap-Yellow-Display/commit/13ced215b7e8f2e90074205df57b2b9ce2a4e932
