### ISSUE TITLE
Add CYD-3248S035C support

### ISSUE THREAD

**Issue by Teapot321** [Fr4nkFletcher/ESP32-Marauder-Cheap-Yellow-Display#66]
Add ESP32-CYD-3248S035C support(CYD with Capactive touch)

**Comment by maxpill** [comment]
@Teapot321 did you manage to add the support yourself?

**Comment by Lgndwilloske** [comment]
think @Fr4nkFletcher is making support for some more boards👍

**Comment by Fr4nkFletcher** [comment]
@Teapot174 done!
