### ISSUE TITLE
Not compatible with a 2.8" capacitive touch screen

### ISSUE THREAD

**Issue by VNEvil** [Fr4nkFletcher/ESP32-Marauder-Cheap-Yellow-Display#69]
Hello everyone!
Does the "ESP32-Marauder-Cheap-Yellow-Display" support the 2.8" ESP32 Capacitive Display (ST7789 240x320 JC2432W328C)? I bought one, but after flashing the firmware, the screen displays the ESP32 Marauder interface, yet I can't tap on any area
Link: https://www.amazon.com/DIYmalls-Touchscreen-ESP-WROOM-32-Development-JC2432W328C/dp/B0D5H84RDB
Thanks!

**Comment by Fr4nkFletcher** [comment]
Check out issue [37](https://github.com/Fr4nkFletcher/ESP32-Marauder-Cheap-Yellow-Display/issues/37)
