### ISSUE TITLE
New features

### ISSUE THREAD

**Issue by Teapot321** [Fr4nkFletcher/ESP32-Marauder-Cheap-Yellow-Display#71]
- Pwangotchi (handshake fishing)
- Wardriving with and without GPS
- DPWO

**Comment by TenoTrash** [comment]
Wow, those will be great addition. Here in Argentina Marauder price is prohibitive, but this project is very affordable. Cheers!

**Comment by Fr4nkFletcher** [comment]
@Teapot321 v1.1.0 coming soon

**Comment by Fr4nkFletcher** [comment]
@Teapot321 done
