### ISSUE TITLE
ESP32 Cheap Yellow Display (CYD) Pinout (ESP32-2432S028R)

### ISSUE THREAD

**Issue by lehuy883773** [Fr4nkFletcher/ESP32-Marauder-Cheap-Yellow-Display#73]
bạn có thể chia sẻ sơ đồ mạch điện không. cảm ơn nhiều

**Comment by Fr4nkFletcher** [comment]
![image](https://github.com/user-attachments/assets/977a2227-36b2-43ab-b4ee-cdba58a24aab)

**Comment by lehuy883773** [comment]
anh bạn anh hiểu sai vấn đề rồi. ý tên là anh hãy cho tôi biết những chấn nối giữa màn hình với chip esp32 thôi :))

**Comment by Jealouscleric** [comment]
That's handy,  what would you suggest for adding gps?

**Comment by Fr4nkFletcher** [comment]
https://github.com/witnessmenow/ESP32-Cheap-Yellow-Display/blob/main/PINS.md
