### ISSUE TITLE
Is there a way to get the code for the UI?

### ISSUE THREAD

**Issue by Fakemayham084** [Fr4nkFletcher/ESP32-Marauder-Cheap-Yellow-Display#76]
i want to add a option to it and could not seem to find the code for it.

**Comment by Fr4nkFletcher** [comment]
What do you mean exactly?

**Comment by Fakemayham084** [comment]
like what is the code for the ui on the screen

**Comment by Fr4nkFletcher** [comment]
TFT-eSPI

https://github.com/Fr4nkFletcher/ESP32-Marauder-Cheap-Yellow-Display/tree/master/esp32_marauder

**Comment by Fr4nkFletcher** [comment]
MenuFunctions

**Comment by Fr4nkFletcher** [comment]
LVGL and TFT-eSPI

https://github.com/Fr4nkFletcher/ESP32-Marauder-Cheap-Yellow-Display/tree/master/esp32_marauder
