### ISSUE TITLE
airtag sniff crash

### ISSUE THREAD

**Issue by zapir69a** [Fr4nkFletcher/ESP32-Marauder-Cheap-Yellow-Display#78]
when i try to do airtag sniff it's just reboots by it self everything else is working properly i tryed a few boards all of them had this problem   

                   -board: cyd 2 usb    
                   -version :1.10  without gps

**Comment by Fr4nkFletcher** [comment]
On it

**Comment by Fr4nkFletcher** [comment]
you wouldn't connect over serial and paste the stack trace when it crashes, would you?

**Comment by Fr4nkFletcher** [comment]
> when i try to do airtag sniff it's just reboots by it self everything else is working properly i tryed a few boards all of them had this problem
> 
> ```
>                -board: cyd 2 usb    
>                -version :1.10  without gps
> ```

flash again and let me know.
