### ISSUE TITLE
CYM Web Flasher only shows version 1.1.0

### ISSUE THREAD

**Issue by martialhax** [Fr4nkFletcher/ESP32-Marauder-Cheap-Yellow-Display#82]
CYM Web Flasher only gives the option to install 1.1.0 and not the latest 1.2.0

**Comment by Fr4nkFletcher** [comment]
Reload your cache -- ctrl+shift+r on the webflasher page

**Comment by martialhax** [comment]
Got it thanks. And thanks for your hard work on this project.
