### ISSUE TITLE
Any chance of adding a Macchanger to the menus

### ISSUE THREAD

**Issue by CriticalO** [Fr4nkFletcher/ESP32-Marauder-Cheap-Yellow-Display#83]
Hello I was wondering if it would be possible to add some kind of macchanger into this device, creating a random Mac and being able to see the current Mac would be awesome although if it's possible and you have enough room (and time), maybe you could also add a custom MAC address option, that would be so handy, thanks for all your hard work so far on this excellent bit of kit, your knowledge and expertise are greatly appreciated, thanks for sharing...

Cheers
Shane

**Comment by Fr4nkFletcher** [comment]
@CriticalO Good idea, will work on this soon

**Comment by CriticalO** [comment]
Thanks very much Frank will look forward to the update, how exciting 😊
