### ISSUE TITLE
support for ESP32-2432S022c

### ISSUE THREAD

**Issue by cosmos1978** [Fr4nkFletcher/ESP32-Marauder-Cheap-Yellow-Display#9]
Is it hard to have this compiling for this board ? ESP32-2432S022c

The platformio board definitions are here https://github.com/rzeldent/platformio-espressif32-sunton/blob/main/esp32-2432S022C.json

**Comment by Fr4nkFletcher** [comment]
> Is it hard to have this compiling for this board ? ESP32-2432S022c
> 
> The platformio board definitions are here https://github.com/rzeldent/platformio-espressif32-sunton/blob/main/esp32-2432S022C.json
> 
> 

Those modules are ST7789 driven, and will not work with this.
